baseurl = "/"
languageCode = "en-US"
title = "Nisha Ramdeep"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "IMG_0539.JPG"
  author = "Nisha Ramdeep"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "nisharamdeep"
  Email         = "nisharamdeep@gmail.com"

## Main Menu
[[menu.main]]
  name = "about"
  weight = 100
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
