---
title: "Project 1_final"
author: "Nisha Ramdeep"
date: "October 20, 2019"
output: html_document
---



<div id="r-markdown" class="section level2">
<h2>R Markdown</h2>
<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com" class="uri">http://rmarkdown.rstudio.com</a>.</p>
<p>When you click the <strong>Knit</strong> button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:</p>
<pre class="r"><code>library(readxl)
library(readr)
library(tidyverse)</code></pre>
<pre><code>## -- Attaching packages --------------------------------------- tidyverse 1.3.0 --</code></pre>
<pre><code>## v ggplot2 3.2.1     v dplyr   0.8.3
## v tibble  2.1.3     v stringr 1.4.0
## v tidyr   1.0.0     v forcats 0.4.0
## v purrr   0.3.3</code></pre>
<pre><code>## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<pre class="r"><code>library(ggplot2)</code></pre>
<pre class="r"><code>state_divorce &lt;- read_excel(&quot;C:/Users/nisha/Downloads/state divorce.xlsx&quot;) #loading document
state_divorce &lt;- state_divorce %&gt;% na.omit %&gt;% select(-c(4:22)) #getting rid of empty cells and selecting 2016 and 2017
state_divorcerate &lt;- state_divorce[-20,] #make sure every dataset has the same rows

state_medianincome &lt;- read_excel(&quot;C:/Users/nisha/Downloads/state median income.xlsx&quot;) #loading document
state_medianincome &lt;- state_medianincome %&gt;% na.omit %&gt;% select(-c(4:12)) #getting rid of empty cells and selecting 2016 and 2017
state_medianincome1 &lt;- state_medianincome[-c(5,6,11,12,15,19,24,27,32,37),] #make sure every dataset has the same rows

state_poverty &lt;- read_excel(&quot;C:/Users/nisha/Downloads/poverty percent.xlsx&quot;) #loading document
state_poverty_rate &lt;- state_poverty[-c(5,6,11,12,15,19,24,27,32,37),] #make sure every dataset has the same rows

state_race &lt;- read_csv(&quot;C:/Users/nisha/Downloads/raw_data.csv&quot;) #loading document</code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   State = col_character(),
##   `2016_White` = col_double(),
##   `2016_Black` = col_double(),
##   `2016_Hispanic` = col_double(),
##   `2016_Asian` = col_double(),
##   `2017_White` = col_double(),
##   `2017_Black` = col_double(),
##   `2017_Hispanic` = col_double(),
##   `2017_Asian` = col_double()
## )</code></pre>
<pre class="r"><code>state_race &lt;- state_race %&gt;% na.omit #getting rid of empty cells
state_race_percent &lt;- state_race[-c(5,6,11,12,15,19,24,31,36),] #make sure every dataset has the same rows

#double check all have the same rows

state_medianincome1 %&gt;% anti_join(state_divorcerate, by=&quot;State&quot;) #nothing</code></pre>
<pre><code>## # A tibble: 0 x 3
## # ... with 3 variables: State &lt;chr&gt;, `2017` &lt;dbl&gt;, `2016` &lt;dbl&gt;</code></pre>
<pre class="r"><code>state_medianincome1 %&gt;% anti_join(state_race_percent, by = &quot;State&quot;) #nothing</code></pre>
<pre><code>## # A tibble: 0 x 3
## # ... with 3 variables: State &lt;chr&gt;, `2017` &lt;dbl&gt;, `2016` &lt;dbl&gt;</code></pre>
<pre class="r"><code>state_medianincome1 %&gt;% anti_join(state_poverty_rate, by=&quot;State&quot;) #nothing</code></pre>
<pre><code>## # A tibble: 0 x 3
## # ... with 3 variables: State &lt;chr&gt;, `2017` &lt;dbl&gt;, `2016` &lt;dbl&gt;</code></pre>
<p>For this project, I wanted to see what factors affect a state’s divorce rate. I thought that if a state had a lower median income, then it would have a higher divorce rate. The same relationship was expected for a state’s poverty percentage and the divorce rate. Lastly, I wanted to see if a state’s race demographic had any effect on any of the other numerical variables. The divorce rate data, median income data, and poverty data were taken from the Census website. The race makeup data was taken from the Kaiser Family Foundation website. Data for poverty was only available for 2016-2017, so the other datasets were restricted to those two years. From the divorce rate dataset, information for California, Colorado, Georgia, Hawaii, Indiana, Louisiana, Minnesota, New Mexico, and Oklahoma was missing. For the the race makeup data, information from Montana was missing. Therefore, these rows were taken out of each of the datasets. NAs were also removed.</p>
<pre class="r"><code>#tidying data

state_divorce_rate &lt;- state_divorcerate %&gt;% pivot_longer(cols=c(2:3), names_to=&quot;year&quot;, values_to=&quot;divorce_rate&quot;)
state_divorce_rate &lt;- state_divorce_rate %&gt;% group_by(State) %&gt;% transmute(avg_divorce_rate=mean(divorce_rate)) %&gt;%
  distinct()

state_median_income &lt;- state_medianincome1 %&gt;% pivot_longer(cols=c(2:3), names_to=&quot;year&quot;, values_to=&quot;median_income&quot;)
state_median_income &lt;- state_median_income %&gt;% group_by(State) %&gt;% transmute(avg_income=mean(median_income))

state_race_percent1 &lt;- state_race_percent %&gt;%
  pivot_longer(cols=c(2:9), names_to=&quot;names&quot;, values_to=&quot;race_percent&quot;) %&gt;%
  separate(names, into=c(&quot;year&quot;,&quot;race&quot;)) %&gt;%
  pivot_wider(names_from=&quot;year&quot;, values_from=&quot;race_percent&quot;) %&gt;%
  rename(&quot;year1&quot;=&quot;2016&quot;) %&gt;%
  rename(&quot;year2&quot;=&quot;2017&quot;) %&gt;%
  mutate(avg_race_percent=((year1+year2)/2)) %&gt;%
  select(State,race,avg_race_percent) %&gt;%
  pivot_wider(names_from=&quot;race&quot;, values_from=&quot;avg_race_percent&quot;) %&gt;%
  mutate(Non_white=1-White) %&gt;%
  select(State, White, Non_white)

final &lt;- state_divorce_rate %&gt;% full_join(state_median_income, by=&quot;State&quot;)
final &lt;- final %&gt;% full_join(state_race_percent1, by=&quot;State&quot;)
final &lt;- final %&gt;% full_join(state_poverty_rate, by=&quot;State&quot;)
final &lt;- final %&gt;% distinct()
final &lt;- final %&gt;% na.omit %&gt;% as.data.frame</code></pre>
<p>Data was tidied by first pivoting the data so that the mean across the two years (2016 and 2017) could be taken easily, and then, using transmute, the column containing the averages was the only one kept. Finally, all 4 datasets were joined into one.</p>
<pre class="r"><code>final %&gt;% select_if(is.numeric) %&gt;% na.omit %&gt;% cor</code></pre>
<pre><code>##                  avg_divorce_rate avg_income       White   Non_white
## avg_divorce_rate       1.00000000 -0.3118164  0.08273335 -0.08273335
## avg_income            -0.31181642  1.0000000 -0.23589748  0.23589748
## White                  0.08273335 -0.2358975  1.00000000 -1.00000000
## Non_white             -0.08273335  0.2358975 -1.00000000  1.00000000
## poverty_percent        0.26481127 -0.7349502 -0.19327364  0.19327364
##                  poverty_percent
## avg_divorce_rate       0.2648113
## avg_income            -0.7349502
## White                 -0.1932736
## Non_white              0.1932736
## poverty_percent        1.0000000</code></pre>
<p>Correlations for the numeric variables were found. These showed a significant negative correlation for a state’s median income from 2016-2017 and its poverty percentage.</p>
<pre class="r"><code>final %&gt;% filter(poverty_percent==max(poverty_percent)|poverty_percent==min(poverty_percent))</code></pre>
<pre><code>##           State avg_divorce_rate avg_income  White Non_white poverty_percent
## 1   Mississippi         3.052541    42270.0 0.5705    0.4295            19.9
## 2 New Hampshire         3.243980    75530.5 0.9085    0.0915             6.5
##      region
## 1     south
## 2 northeast</code></pre>
<p>The state with the highest percentage of their population in poverty was Mississippi. The state with the lowest was New Hampshire.</p>
<pre class="r"><code>final %&gt;% summarize(avg_poverty_rate_national=mean(poverty_percent))</code></pre>
<pre><code>##   avg_poverty_rate_national
## 1                  12.12439</code></pre>
<p>According to this data, the national poverty percentage was around 12.12%.</p>
<pre class="r"><code>final %&gt;% summarize(median_divorce_rate_national=median(avg_divorce_rate))</code></pre>
<pre><code>##   median_divorce_rate_national
## 1                     3.052541</code></pre>
<p>According to this data, the median divorce rate nationally was 3.05. This means that for every 1000 marriages nationally, around 3 end in divorce.</p>
<pre class="r"><code>final %&gt;% arrange(avg_income) %&gt;% head(6)</code></pre>
<pre><code>##           State avg_divorce_rate avg_income  White Non_white poverty_percent
## 1   Mississippi         3.052541    42270.0 0.5705    0.4295            19.9
## 2 West Virginia         3.618049    44873.0 0.9250    0.0750            17.8
## 3      Arkansas         3.823038    47368.0 0.7275    0.2725            15.3
## 4      Kentucky         3.757386    48358.5 0.8505    0.1495            15.1
## 5       Alabama         3.719604    49167.0 0.6590    0.3410            16.1
## 6         Maine         3.327395    51260.0 0.9365    0.0635            13.1
##      region
## 1     south
## 2     south
## 3     south
## 4     south
## 5     south
## 6 northeast</code></pre>
<p>The state with the lowest median income from 2016-2017 was Mississippi. Looking at this data, it seems that Southern states have some of the lowest median incomes in the country.</p>
<pre class="r"><code>final %&gt;% select(-State) %&gt;% group_by(region) %&gt;% mutate(mean_divorce_rate_region=mean(avg_divorce_rate)) %&gt;% 
  arrange(mean_divorce_rate_region) %&gt;%
  select(region, mean_divorce_rate_region) %&gt;%
  distinct()</code></pre>
<pre><code>## # A tibble: 4 x 2
## # Groups:   region [4]
##   region    mean_divorce_rate_region
##   &lt;chr&gt;                        &lt;dbl&gt;
## 1 midwest                       2.61
## 2 northeast                     2.85
## 3 south                         3.21
## 4 west                          3.74</code></pre>
<p>The average divorce rate per region is given here. It looks like the divorce rate in the Midwestern states is the lowest, while divorce rates in the Western states are the highest.</p>
<pre class="r"><code>final %&gt;% group_by(region) %&gt;% count()</code></pre>
<pre><code>## # A tibble: 4 x 2
## # Groups:   region [4]
##   region        n
##   &lt;chr&gt;     &lt;int&gt;
## 1 midwest      10
## 2 northeast     9
## 3 south        14
## 4 west          8</code></pre>
<pre class="r"><code>final %&gt;% group_by(region) %&gt;% mutate(mean_income_region=mean(avg_income)) %&gt;% mutate(sd_region=sd(avg_income)) %&gt;%
  arrange(mean_income_region) %&gt;% select(region, mean_income_region, sd_region) %&gt;% distinct()</code></pre>
<pre><code>## # A tibble: 4 x 3
## # Groups:   region [4]
##   region    mean_income_region sd_region
##   &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;
## 1 south                 56203.    11187.
## 2 midwest               59019.     2402.
## 3 west                  63679.     7256.
## 4 northeast             66102.     7868.</code></pre>
<p>The South has the largest number of states in the dataste, while the West has the least amount. The Northeast has the highest median income, and the South has the lowest median income. The Southern states, while having the lowest median income, have the highest standard deviation.</p>
<pre class="r"><code>final %&gt;% ggplot(aes(x=State, y=avg_divorce_rate, color=region))+
  geom_point(size=2)+
  theme(axis.text.x = element_text(angle = 50, hjust = 1))</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p><em>Divorce rates per state were given. They were grouped by region. There doesn’t appear to be any correlation between the region and the average divorce rate. Although, the Western states have some of the highest, and the Midwestern states have some of the lowest.</em></p>
<pre class="r"><code>final %&gt;% group_by(region) %&gt;% mutate(poverty_rate_region=mean(poverty_percent)) %&gt;%
  ggplot(aes(region))+
  geom_bar(aes(y=avg_divorce_rate,fill=poverty_rate_region),stat=&quot;summary&quot;,fun.y=&quot;mean&quot;)+
  theme(axis.text.x = element_text(angle = 45,hjust = 1))</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p><em>This shows that there isn’t a relationship between the poverty rate and the divorce rate. The region with the lowest poverty rate (Northeast) does not have the lowest divorce rate.</em></p>
<pre class="r"><code>final %&gt;% ggplot(aes(x=Non_white, y=poverty_percent,color=region))+
  geom_point(size=2)</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p><em>The states with the highest amount of diversity, while up there, do not necessarily have the highest amount of poverty. Similarly, states with less diversity do not seem to have lower amounts of poverty. The South, again, seems to struggle with higher poverty rates, while the Northeast is generally low.</em></p>
<pre class="r"><code>final %&gt;% ggplot(aes(x=region,y=avg_income))+
  geom_boxplot()+
  geom_jitter(alpha=.5, aes(color=White))</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p><em>In this plot, the median incomes of the states in each region were plotted to show their distribution. Layered on top of that was the percentage of White people was layered on top. There does not seem to be a relationship between the percentage of White people in the state and the median income of the region.</em></p>
<pre class="r"><code>centers &lt;- final %&gt;%
  mutate(cluster=sample(c(&quot;1&quot;,&quot;2&quot;,&quot;3&quot;),41,replace=T)) %&gt;%
  group_by(cluster)%&gt;%
  summarize(poverty_percent=mean(poverty_percent),avg_divorce_rate=mean(avg_divorce_rate))

ggplot(final)+geom_point(aes(poverty_percent, avg_divorce_rate))+
  geom_point(data=centers,aes(poverty_percent,avg_divorce_rate,fill=&quot;&quot;),color=&quot;black&quot;,size=4)+
  scale_fill_manual(name=&quot;cluster&quot;,values = &quot;black&quot;)</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<pre class="r"><code>suppressWarnings(expr= for(i in 1:1000){
iter&lt;-final%&gt;%mutate(dist1=sqrt((poverty_percent-centers$poverty_percent[1])^2+(avg_divorce_rate-centers$avg_divorce_rate[1])^2),
              dist2=sqrt((poverty_percent-centers$poverty_percent[2])^2+(avg_divorce_rate-centers$avg_divorce_rate[2])^2),
              dist3=sqrt((poverty_percent-centers$poverty_percent[3])^2+(avg_divorce_rate-centers$avg_divorce_rate[3])^2))%&gt;%
  rowwise()%&gt;%mutate(cluster=as.factor(which.min(c(dist1,dist2,dist3))))

centers&lt;-iter%&gt;%group_by(cluster)%&gt;%summarize(poverty_percent=mean(poverty_percent),
                                              avg_divorce_rate=mean(avg_divorce_rate))
})
ggplot(iter)+geom_point(aes(poverty_percent,avg_divorce_rate,color=cluster))+
  geom_point(data=centers,aes(poverty_percent,avg_divorce_rate),color=&quot;black&quot;,size=4)</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre class="r"><code>clust_dat &lt;- final%&gt;%select(poverty_percent, avg_divorce_rate)
kmeans1&lt;-clust_dat%&gt;%kmeans(3)
kmeans1</code></pre>
<pre><code>## K-means clustering with 3 clusters of sizes 9, 22, 10
## 
## Cluster means:
##   poverty_percent avg_divorce_rate
## 1        15.97778         3.304734
## 2        11.95000         3.155807
## 3         9.04000         2.746979
## 
## Clustering vector:
##  [1] 1 2 1 1 3 2 1 2 2 2 3 2 1 2 3 3 2 1 2 3 2 3 3 2 1 2 2 2 2 2 1 2 2 2 3 3 2 2
## [39] 1 3 2
## 
## Within cluster sum of squares by cluster:
## [1] 26.65744 25.27128 20.50101
##  (between_SS / total_SS =  76.1 %)
## 
## Available components:
## 
## [1] &quot;cluster&quot;      &quot;centers&quot;      &quot;totss&quot;        &quot;withinss&quot;     &quot;tot.withinss&quot;
## [6] &quot;betweenss&quot;    &quot;size&quot;         &quot;iter&quot;         &quot;ifault&quot;</code></pre>
<pre class="r"><code>kmeansclust&lt;-clust_dat%&gt;%mutate(cluster=as.factor(kmeans1$cluster))
kmeansclust%&gt;%ggplot(aes(poverty_percent,avg_divorce_rate,color=cluster))+geom_point()</code></pre>
<p><img src="/Project1_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>
