---
title: BlogPost1
author: ''
date: '2019-12-15'
slug: blogpost1
categories: []
tags: []
description: ''
---

##Using Python

In class, we have been using Python to do a couple of interesting things. These include using regular expressions (regex) to find matches of certain characters in strings, almost like ctrl+f.

For example:

```{python}
import re

string = "We have to extract these numbers 12, 47, 48 The integers numbers are also interesting: 189 2036 314\',\' is a separator, so please extract these numbers 125,789,1450 and also these 564,90456 We like to offer you 7890$ per month in order to complete this task... we are joking"

re.findall(r'\d+', string)

```

Given that simple string, we were able to use a regex to extract all of the numbers. This can be useful when you need certain information from a large document quickly.

We can also use it for slightly more complicated strings.

For example:

```{python}
string1 = r"We try to quantitatively capture these characteristics by defining a set of indexes,\
which can be computed using the mosaic image and the corresponding ground truth: \
\begin{itemize} \
    \item $\mu_{A_T}$ and $\sigma_{A_T}$, the mean and standard deviation of the tiles area $A_T$, respectively; \
    \item $\rho_\text{filler}$, the ratio between the filler area and the overall mosaic are, computed as \
$\rho_\text{filler}=\frac{\sum_{T \in \mathcal{T} A_T}}{A}$, being $A$ the area of the mosaic; \
    \item \todo{does it worth?}; \
    \item \todo{does it worth?}; \
    \item $\mu_{C_T}$, the mean of the tiles \emph{color dispersion} $C_T$, \
being $C_T = \sigma_R+\sigma_G+\sigma_B$, where $\sigma_R$, $\sigma_G$ and $\sigma_B$ are the \
standard deviation of the red, green and blue channel values of the pixels within the tile $T$.\
After applying a method to an image, we compare the segmented image (i.e., the result) \
against the ground truth and assess the performance according to the following three metrics: \
\begin{itemize} \
    \item average tile precision $P$ \
    \item average tile recall $R$ \
    \item tile count error $C$"

re.findall(r'\$[^$]+\$', string1)
```

This time we used a regex to extract all of the latex math-mode text from a large string.

We also used Python to find the different k-mers that could be obtained from a DNA sequence.

For example:

```{python}
my_seq = "CAGCCCAATCAGGCTCTACTGCCACTAAACTTACGCAGGATATATTTACGCCGACGTACT"

def count_kmers(read):

    k = 3
    count = {}
    num = len(read) - 2
    for i in range(num):
        threemer = read[i:i+k]
        if threemer not in count:
            count[threemer] = 0
        count[threemer] += 1
    return count
count_kmers(my_seq)

```


Given that sequence, we were able to generate a dictionary with all of the possible k-mers.

Overall, Python has been very interesting, and I hope to continue to learn more!